services:
  - type: web
    name: scholarship-form-backend
    runtime: node
    repo: https://github.com/zaishtagroupofcreatives/Scholarship-Form
    branch: main
    healthCheckPath: /
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: password
    buildFilter:
      paths:
        - server/**
        - package.json
        - render.yaml
    buildCommand: "cd server && npm install"
    startCommand: "cd server && node server.js"
